import type {
  SnkrsMapCenter,
  SnkrsMapCity,
  SnkrsStoreLocation,
  SnkrsUserLocation,
} from "@/lib/snkrs/types";

export const snkrsMapCenters: Record<SnkrsMapCity, SnkrsMapCenter> = {
  "taiwan-north": {
    lat: 24.97,
    lng: 121.2,
    zoom: 10,
  },
  shanghai: {
    lat: 31.23,
    lng: 121.47,
    zoom: 12,
  },
};

export const snkrsUserLocations: Record<SnkrsMapCity, SnkrsUserLocation> = {
  "taiwan-north": {
    label: "桃園市桃園區中寧街50巷10號",
    city: "桃園市桃園區",
    lat: 25.0186979,
    lng: 121.2956619,
  },
  shanghai: {
    label: "我的位置",
    city: "Shanghai",
    lat: 31.23,
    lng: 121.47,
  },
};

export const snkrsTaiwanNorthStores: SnkrsStoreLocation[] = [
  {
    id: "store-tyo-1",
    name: "Nike Unite 桃園華泰",
    city: "桃園",
    distanceKm: 3,
    shortLabel: "NIKE",
    lat: 25.013,
    lng: 121.212,
    address: "桃園市中壢區春德路189號\nTaoyuan, 320",
    detailUrl: "#",
  },
  {
    id: "store-tyo-2",
    name: "INVINCIBLE 桃園",
    city: "桃園",
    distanceKm: 7,
    shortLabel: "INVC",
    lat: 24.993,
    lng: 121.302,
    address: "桃園市桃園區中正路112號\nTaoyuan, 330",
    detailUrl: "#",
  },
  {
    id: "store-hsz-1",
    name: "JUICE 新竹",
    city: "新竹",
    distanceKm: 18,
    shortLabel: "JUCE",
    lat: 24.803,
    lng: 120.971,
    address: "新竹市東區勝利路86號\nHsinchu, 300",
    detailUrl: "#",
  },
  {
    id: "store-hsz-2",
    name: "ABC-MART 竹北",
    city: "新竹",
    distanceKm: 20,
    shortLabel: "ABC",
    lat: 24.837,
    lng: 121.013,
    address: "新竹縣竹北市光明六路東一段251號\nHsinchu, 302",
    detailUrl: "#",
  },
  {
    id: "store-tpe-1",
    name: "PHANTACi 台北",
    city: "台北",
    distanceKm: 37,
    shortLabel: "PHAN",
    lat: 25.042,
    lng: 121.552,
    address: "台北市大安區忠孝東路四段181巷35弄27號\nTaipei, 106",
    detailUrl: "#",
  },
  {
    id: "store-ntp-1",
    name: "UNDEFEATED 新北",
    city: "新北",
    distanceKm: 41,
    shortLabel: "UNDF",
    lat: 25.011,
    lng: 121.463,
    address: "新北市板橋區中山路一段112號\nNew Taipei, 220",
    detailUrl: "#",
  },
];

export const snkrsShanghaiStores: SnkrsStoreLocation[] = [
  {
    id: "store-exit-1",
    name: "EXI.T",
    city: "Shanghai",
    distanceKm: 682,
    shortLabel: "EX!T",
    lat: 31.191,
    lng: 121.507,
    address: "上海市浦東新區東昌路500弄1-9號浦建太古里S-L2-30號\nShanghai, 200135",
    detailUrl: "#",
  },
  {
    id: "store-exit-2",
    name: "EXI.T",
    city: "Shanghai",
    distanceKm: 683,
    shortLabel: "EX!T",
    lat: 31.219,
    lng: 121.434,
    address: "上海市靜安區愚園路68號\nShanghai, 200040",
    detailUrl: "#",
  },
  {
    id: "store-honor23",
    name: "HONOR 23",
    city: "Shanghai",
    distanceKm: 687,
    shortLabel: "H23",
    lat: 31.247,
    lng: 121.501,
    address: "上海市黃浦區中山東一路23號\nShanghai, 200002",
    detailUrl: "#",
  },
  {
    id: "store-undftd",
    name: "UNDFTD",
    city: "Shanghai",
    distanceKm: 688,
    shortLabel: "UNDF",
    lat: 31.238,
    lng: 121.451,
    address: "上海市徐匯區淮海中路999號\nShanghai, 200031",
    detailUrl: "#",
  },
  {
    id: "store-unik",
    name: "UNIK",
    city: "Shanghai",
    distanceKm: 688,
    shortLabel: "UNIK",
    lat: 31.203,
    lng: 121.468,
    address: "上海市浦東新區世紀大道1192號\nShanghai, 200122",
    detailUrl: "#",
  },
  {
    id: "store-soulgoods",
    name: "SOULGOODS",
    city: "Shanghai",
    distanceKm: 688,
    shortLabel: "SOUL",
    lat: 31.226,
    lng: 121.486,
    address: "上海市靜安區成都北路333號\nShanghai, 200003",
    detailUrl: "#",
  },
];
